plugins {
    id "com.android.application"
}

android {
    namespace "com.bychaeun.company"
    compileSdk 35

    defaultConfig {
        applicationId "com.bychaeun.company"
        minSdk 23
        targetSdk 35
        versionCode 13
        versionName "12.0.1"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
